name: scooby
description: "A Flutter project for my EV Scooty."

publish_to: 'none'


environment:
  sdk: ^3.11.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  wave: ^0.2.2
  flutter_blue_plus: ^2.3.3
  permission_handler: ^12.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/scooty.png
    - lib/assets/charge_ev.png
    - lib/assets/charge_ev_trans.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.jpg"
  min_sdk_android: 21